server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou2
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 192.168.72.129
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.72.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 50 # 10秒不发送就过期
    prefer-ip-address: true # 保证拿到的是Ip
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  type-aliases-package: com.leyou.user.pojo
