server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api   # 添加路由前缀
  routes:
      item-service: /item/**
      search-service: /search/**
      user-service: /user/**
      upload-service:
          path: /upload/**
          serviceId: upload-service
          strip-prefix: false  #去掉前缀
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 1000 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 10 # 同一服务不同实例的重试次数
  MaxAutoRetries: 10 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 1000 # 熔断超时时长：10000ms