server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou2
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 192.168.72.129
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
      exchange: ly.item.exchange
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 50 # 10秒不发送就过期
    prefer-ip-address: true # 保证拿到的是Ip
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:  #日志输出打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl